// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yswuuvhmcppsmasspgzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzd3V1dmhtY3Bwc21hc3NwZ3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzYxNzksImV4cCI6MjA3Njc1MjE3OX0.YuRXFZ8nH9VEALtrLV8g9X-vfA2F1sPR86zybyE0nHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});